#######################################
# Moonraker integration               #
# Copyright (C) 2022 Sylwester Hojdak #
#######################################

camera:
  - platform: generic
    name: "Neptune_3_Thumbnail"
    still_image_url: http://<moonraker_ip_adress_or_hostname>:7125/server/files/gcodes/{{ states(('sensor.neptune3_current_print')).split('/')[0] + "/" if '/' in states(('sensor.neptune3_current_print')) !=0 else ""}}{{ states.sensor.Neptune3_file_metadata.attributes["thumbnails"][1]["relative_path"] }}
    verify_ssl: false

sensor:

  - platform: rest
    name: Neptune3_sensor
    resource: "http://<moonraker_ip_adress_or_hostname>:7125/printer/objects/query?heater_bed&extruder&print_stats&toolhead&display_status&virtual_sdcard&gcode_move&webhooks&temperature_sensor mcu_temp&temperature_sensor raspberry_pi&filament_motion_sensor filament_sensor"
    json_attributes_path: "$.result.status"
    json_attributes:
      - heater_bed
      - extruder
      - print_stats
      - toolhead
      - display_status
      - virtual_sdcard
      - gcode_move
      - webhooks
      - temperature_sensor mcu_temp
      - temperature_sensor raspberry_pi
      - "filament_motion_sensor filament_sensor"
    value_template: >-
      {{ 'OK' if ('result' in value_json) else None }}
    force_update: true
    scan_interval: 1

  - platform: rest
    scan_interval: 5
    resource_template: "http://<moonraker_ip_adress_or_hostname>:7125/server/files/metadata?filename={{ states(('sensor.neptune3_current_print')) }}"
    name: Neptune3_file_metadata
    json_attributes_path: "$.result"
    json_attributes:
      - layer_height
      - object_height
      - thumbnails
    value_template: "OK"

  - platform: rest
    scan_interval: 15
    name: klipper_preview_path
    resource_template: "http://<moonraker_ip_adress_or_hostname>:7125/server/files/metadata?filename={{ states(('sensor.neptune3_current_print')) }}"
    json_attributes_path: "$.result.thumbnails.[2]"
    json_attributes:
      - relative_path
      - width
      - height
      - size
    value_template: "OK"

  - platform: template
    sensors:
      neptune3_state:
        friendly_name: "Printer State"
        value_template: >-
          {{ states.sensor.neptune3_sensor.attributes['print_stats']['state'] if states('sensor.neptune3_sensor') != 'unknown' else None }}
        icon_template: >
          {% set val =  states.sensor.neptune3_sensor.attributes["print_stats"]["state"]  %}
          {% if val == 'standby' %}
            mdi:sleep
          {% elif val == 'error' %}
            mdi:alert-circle-outline
          {% elif val == 'printing' %}
            mdi:printer-3d-nozzle-outline
          {% elif val == 'paused' %}
            mdi:pause-circle-outline
          {% elif val == 'complete' %}
            mdi:printer-3d
          {% else %}
            mdi:help-circle-outline
          {% endif %}

      neptune3_current_print:
        friendly_name: "Current Print"
        value_template: >-
          {{ states.sensor.neptune3_sensor.attributes['print_stats']['filename'] if states('sensor.neptune3_sensor') != 'unknown' else None }}

      neptune3_current_progress:
        friendly_name: "Progress"
        unit_of_measurement: '%'
        icon_template: mdi:cube-send
        value_template: >-
          {{ (states.sensor.neptune3_sensor.attributes['display_status']['progress'] * 100) | round(1) if states('sensor.neptune3_sensor') != 'unknown' else None }}

      neptune3_print_time:
        friendly_name: "Time Elapsed"
        icon_template: mdi:clock-start
        value_template: >-
          {{ states.sensor.neptune3_sensor.attributes['print_stats']['print_duration'] | timestamp_custom("%H:%M:%S", 0) if states('sensor.neptune3_sensor') != 'unknown' else None }}

      neptune3_time_remaining:
        friendly_name: "Time Remaining"
        icon_template: mdi:clock-end
        value_template: >-
          {{ (((states.sensor.neptune3_sensor.attributes['print_stats']['print_duration'] / states.sensor.neptune3_sensor.attributes['display_status']['progress'] - states.sensor.neptune3_sensor.attributes['print_stats']['print_duration']) if states.sensor.neptune3_sensor.attributes['display_status']['progress'] > 0 else 0)) | timestamp_custom("%H:%M:%S", 0) if states('sensor.neptune3_sensor') != 'unknown' else None }}

      neptune3_eta:
        friendly_name: "ETA"
        icon_template: mdi:clock-outline
        value_template: >-
          {{ (as_timestamp(now()) + 1 * 60 * 60 + ((states.sensor.neptune3_sensor.attributes['print_stats']['print_duration'] / states.sensor.neptune3_sensor.attributes['display_status']['progress'] - states.sensor.neptune3_sensor.attributes['print_stats']['print_duration']) if states.sensor.neptune3_sensor.attributes['display_status']['progress'] > 0 else None)) | timestamp_custom("%a %d %b, %H:%M:%S", 0) if states('sensor.neptune3_sensor') != 'unknown' else None }}

      neptune3_hotend_temp:
        friendly_name: "Hotend Temperature"
        icon_template: mdi:thermometer
        value_template: >-
          {{ [(states.sensor.neptune3_sensor.attributes['extruder']['temperature'] | float | round(1) | string), " / ", (states.sensor.neptune3_sensor.attributes['extruder']['target'] | float | round(1) | string)] | join if states('sensor.neptune3_sensor') != 'unknown' else None }}

      neptune3_bed_temp:
        friendly_name: "Bed Temperature"
        icon_template: mdi:thermometer
        value_template: >-
          {{ [(states.sensor.neptune3_sensor.attributes['heater_bed']['temperature'] | float | round(1) | string), " / ", (states.sensor.neptune3_sensor.attributes['heater_bed']['target'] | float | round(1) | string)] | join if states('sensor.neptune3_sensor') != 'unknown' else None }}

      neptune3_mcu_pi_temp:
        friendly_name: "MCU & Pi Temperature"
        icon_template: mdi:thermometer
        value_template: >-
          {{ [(states.sensor.neptune3_sensor.attributes['temperature_sensor mcu_temp']['temperature'] | float | round(1) | string), " / ", (states.sensor.neptune3_sensor.attributes['temperature_sensor raspberry_pi']['temperature'] | float | round(1) | string)] | join if states('sensor.neptune3_sensor') != 'unknown' else None }}

      neptune3_current_height:
        friendly_name: "Current Height"
        value_template: '{{ states.sensor.neptune3_sensor.attributes["gcode_move"]["gcode_position"][2]  | float | round(2) }}'
        unit_of_measurement: "mm"
        icon_template: mdi:arrow-collapse-down

      neptune3_state_message:
        friendly_name: "State Message"
        value_template: '{{ states.sensor.neptune3_sensor.attributes["webhooks"]["state_message"] }}'

      neptune3_height_progress:
        friendly_name: "Height Progress"
        value_template: >-
          {{ [(states.sensor.neptune3_sensor.attributes["gcode_move"]["gcode_position"][2]  | float | round(2) | string), " / ", (states.sensor.neptune3_file_metadata.attributes["object_height"] | float | string)] | join if states('sensor.neptune3_sensor') != 'unknown' else None }}
        icon_template: mdi:arrow-expand-vertical

      neptune3_layer_progress:
        friendly_name: "Layer Progress"
        value_template: >-
          {{ [(states("sensor.neptune3_current_height")|float / states("sensor.3d_printer_layer_height")|float)|round(0), " / ", (states("sensor.3d_printer_object_height")|float / states("sensor.3d_printer_layer_height")|float)|round(0)] | join if states('sensor.neptune3_sensor') != 'unknown' else None }}
        icon_template: mdi:layers-triple-outline

      neptune3_layer_height:
        friendly_name: "Layer Height"
        value_template: '{{ states.sensor.Neptune3_file_metadata.attributes["layer_height"] | float }}'
        unit_of_measurement: "mm"
        icon_template: mdi:arrow-collapse-vertical

      neptune3_object_height:
        friendly_name: "Object Height"
        value_template: '{{ states.sensor.Neptune3_file_metadata.attributes["object_height"] | float }}'
        unit_of_measurement: "mm"
        icon_template: mdi:arrow-expand-vertical

      neptune3_current_layer:
        friendly_name: "Current Layer"
        value_template: '{{ (states("sensor.3d_printer_current_height")|float / states("sensor.3d_printer_layer_height")|float)|round(0) }}'

      neptune3_total_layers:
        friendly_name: "Total Layers"
        value_template: '{{ (states("sensor.3d_printer_object_height")|float / states("sensor.3d_printer_layer_height")|float)|round(0) }}'

      neptune3_object_thumbnails:
        friendly_name: "Object Thumbnails"
        value_template: '{{ states(("sensor.neptune3_current_print")).split("/")[0] + "/" if "/" in states(("sensor.neptune3_current_print")) !=0 else ""}}{{ states.sensor.Neptune3_file_metadata.attributes["thumbnails"][1]["relative_path"] }}'
        icon_template: mdi:image

binary_sensor:
  - platform: template
    sensors:
      neptune3_filament:
        friendly_name: "Filament Sensor"
        icon_template: mdi:printer-3d-nozzle-alert
        device_class: motion
        value_template: >-
          {{ states.sensor.neptune3_sensor.attributes["filament_motion_sensor filament_sensor"]["filament_detected"] }}

rest_command:
  neptune3_emergency_stop:
    url: "http://<moonraker_ip_adress_or_hostname>:7125/printer/emergency_stop"
    method: post
  neptune3_restart:
    url: "http://<moonraker_ip_adress_or_hostname>:7125/printer/firmware_restart"
    method: post
  neptune3_cancel:
    url: "http://<moonraker_ip_adress_or_hostname>:7125/printer/print/cancel"
    method: post
  neptune3_pause:
    url: "http://<moonraker_ip_adress_or_hostname>:7125/printer/print/pause"
    method: post
  neptune3_resume:
    url: "http://<moonraker_ip_adress_or_hostname>:7125/printer/print/resume"
    method: post
